name: Comment on All Existing Issues

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  comment-all-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      
    steps:
      - name: Comment on all open issues
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            
            for (const issue of issues.data) {
              // Skip pull requests (they appear as issues in the API)
              if (issue.pull_request) continue;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `👋 Thank you for raising this issue! Our team will review it soon. \n\n For a list of repositories that contribute towards Hacktoberfest refer [this](https://github.com/DhanushNehru/Hacktoberfest2025/discussions/522) and also join this [discussion](https://github.com/DhanushNehru/Hacktoberfest2025/discussions/405)`
              });
              
              // Add delay to avoid rate limiting
              await new Promise(resolve => setTimeout(resolve, 1000));
            }
